blank_issues_enabled: false
contact_links:
  - name: Technical support
    url: https://discord.gg/sKeVmR3
    about: Having technical problems with IW4x²? Ask us on discord and we might be able to help you!
